language: python
python:
  - "3.4"
before_install:
  - openssl aes-256-cbc -K $encrypted_c726f3711a39_key -iv $encrypted_c726f3711a39_iv -in travis.collab-demos.jspaaks.key.enc -out travis.collab-demos.jspaaks.key -d
install:
  - chmod 600 travis.collab-demos.jspaaks.key
  - eval `ssh-agent -s`
  - ssh-add travis.collab-demos.jspaaks.key
  # tell git who is doing this commit
  - git config user.email "j.spaaks@esciencecenter.nl"
  - git config user.name "Travis CI"
script:
  # command to build the readme.md from readme-data.json using src/makereadme.py
  - bash ./deploy.sh
