language: python
python:
  - "3.4"
before_install:
  # decrypt the private key file .travis.collab-demos.key.enc using another set
  # of key files from https://travis-ci.org/jspaaks/collab-demos/settings. Note
  # that those key files were put there when I executed TODO FIXME locally.
  - openssl aes-256-cbc -K $encrypted_c726f3711a39_key -iv $encrypted_c726f3711a39_iv -in .travis.collab-demos.key.enc -out .travis.collab-demos.key -d
install:
  # set file permissions on .travis.collab-demos.key so that Travis can read the key file
  - chmod 400 .travis.collab-demos.key
  - eval `ssh-agent -s`
  - ssh-add .travis.collab-demos.key
  # tell git who is doing this commit
  - git config user.email "j.spaaks@esciencecenter.nl"
  - git config user.name "Travis CI"
  # define where the origin lives (github) and how travis should reach it (over ssh)
  - git remote set-url origin git@github.com:jspaaks/collab-demos.git
script:
  # command to build the README.md from readme-data.json using src/makereadme.py
  - bash ./deploy.sh
