language: python
python:
  - "3.4"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to build the readme.md from readme-data.json using src/makereadme.py
script: src/makereadme.py 

