language: python
python:
  - "3.4"
before_install:
  - openssl aes-256-cbc -K $encrypted_c726f3711a39_key -iv $encrypted_c726f3711a39_iv -in .travis.collab-demos.key.enc -out .travis.collab-demos.key -d
install:
  - chmod 600 .travis.collab-demos.key
  - eval `ssh-agent -s`
  - ssh-add .travis.collab-demos.key
  # tell git who is doing this commit
  - git config user.email "j.spaaks@esciencecenter.nl"
  - git config user.name "Travis CI"
  # define where the origin lives (github) and how travis should reach it (over ssh)
  - git remote set-url origin git@github.com:jspaaks/collab-demos.git
script:
  # command to build the README.md from readme-data.json using src/makereadme.py
  - bash ./deploy.sh
